version: '3'

services:

  app:

    image: node:9
    working_dir: /var/tmp

    entrypoint: "npm"

    expose:
      - "8080"

    volumes:
      - ./app:/var/tmp
      - ./node_modules:node_modules:rw
