version: '3'

services:

  core:
    image: mrboots/pingpong:latest
    volumes:
      - ./URLS:/var/URLS
      - ./log:/var/log:rw
    environment:
      - CRON_STRINGS=*/10 * * * * /bin/sh /scripts/run.sh

  server.local:
    image: pingpong-api
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./server/:/var/pingpong
      - ./log/pingpong.log:/var/DB
