version: '3'

services:

  app:

    image: node:latest
    working_dir: /var/tmp

    command: ["npm"]

    expose:
      - "8080"

    environment:
      - SSH_AUTH_SOCK=/ssh_agent

    volumes:
      - $SSH_AUTH_SOCK:/ssh_agent
      - ./app:/var/tmp
      - ./.git:/var/tmp/.git:rw
      - ./app/node_modules:/var/tmp/node_modules:rw
